### ISSUE TITLE
Make grouping work with other packages

### ISSUE THREAD

**Issue by amritk** [rschristian/tailwind-grouping#1]
Might not be in scope, but it would be sweet if we can get this working with other packages. Might just need some tweaks to the regex.
- [cva/clsx/cx](https://github.com/joe-bell/cva)
- [tailwind merge](https://github.com/dcastil/tailwind-merge)
- [Prettier for tailwind](https://github.com/tailwindlabs/prettier-plugin-tailwindcss)

I can look into what might be needed to get this working.

Otherwise awesome plugin! I was thinking to build the exact same thing then I found this one ❤️

**Comment by rschristian** [comment]
Glad to hear it might be of use!

I'm not sure how many of those would be in the scope tbh. At the moment this (largely) doesn't use blind regex patterns for detecting grouped classes, but instead limits itself to JSX attributes as detected by Babel. When you start expanding to every string in the module perf tends to go down quite a bit and there's likely to be a fair number of false positives that would be difficult to detect.

`clsx`'s use case can largely be replaced by template literals, which are supported here (and comes with 0 overhead). I'm not sure what the issue with Tailwind's Prettier plugin would be, does it trip over grouped classes? That would likely have to be fixed upstream, I don't think there's anything that can be done here.

**Comment by amritk** [comment]
Yea prettier drops the grouping `hover:(bg-red gap-2 mt-9 p-64)` -> `hover:(bg-red p-64) mt-9 gap-2` I opened a discussion on that side. Yea it would drop performance, I might just fork it and see if I can get something going

**Comment by rschristian** [comment]
It should be pretty easy, you're likely just going to want to expand [this](https://github.com/rschristian/tailwind-grouping/blob/9497e3ccfa8f76a126ae277156bc5d794e6e7794/packages/babel/index.js#L70) to also include string literals and template elements

**Comment by amritk** [comment]
Thanks, but I think prettier will be the big roadblock, going to try and solve that one first. Feel tree to close this issue if you like, or keep it open for tracking and if anyone else comes along.

**Comment by amritk** [comment]
So the prettier part wasn't hard for my use case, minor tweak to the regex but it broke the general build. So I might just maintain a little fork of it. Then I just gotta do the CVA bits and it should be good to go

**Comment by rschristian** [comment]
Sounds good! Let me know if you need any help

**Comment by amritk** [comment]
Alright PR is up, lets see what they say

https://github.com/tailwindlabs/prettier-plugin-tailwindcss/pull/227

**Comment by rschristian** [comment]
Going to close this on out, as I don't think there's anything actionable.
